# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b8f6a82c857a4e1920062bc7ae42b0073c888aaa4db28b3ce149544c182e7442914b00b5f2f9f82083ad8b79b033cfe3bfc9975bfb5abdf9b6286e1422cbe22

test:
  secret_key_base: 13a01f3897bb33bb427d6ac28f0b136e48e0ff9f832805930e6b9b81cb21882be681158ead127189ab52360337695b0f4f253e4fd94fa3fe71f2942cfcff1b0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
